# Fase 1 - Data Analytics - Analise de dados Storytelling
## Aula 3 - Analisando dados com python I

In [10]:
# Bibliotecas para manipulação e análise de dados
import pandas as pd
import numpy as np

# Bibliotecas para visualização de dados
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [11]:
# Lê o arquivo Excel e armazena no DataFrame df_dengue
df_dengue = pd.read_excel('/content/sample_data/Base de Dados Dengue.xlsx')

# Exibe as primeiras 5 linhas do DataFrame (índice começa em 0)
df_dengue.head()

               municipio  uf data_infeccoes  qtd_infeccoes
0  ALTA FLORESTA D'OESTE  RO     2013-01-01             34
1  ALTA FLORESTA D'OESTE  RO     2013-02-01             44
2  ALTA FLORESTA D'OESTE  RO     2013-03-01             15
3  ALTA FLORESTA D'OESTE  RO     2013-04-01              4
4  ALTA FLORESTA D'OESTE  RO     2013-05-01              3

In [12]:
# Exibe as últimas 5 linhas do DataFrame
df_dengue.tail()

       municipio  uf data_infeccoes  qtd_infeccoes
728767  BRASILIA  DF     2023-08-01            939
728768  BRASILIA  DF     2023-09-01            843
728769  BRASILIA  DF     2023-10-01            686
728770  BRASILIA  DF     2023-11-01           1300
728771  BRASILIA  DF     2023-12-01           5603

## Aula 3 - Analisando dados com python I