In [40]:
#importando a biblioteca pandas
import pandas as pd

In [41]:

dados = pd.read_csv("/content/sample_data/A150850189_28_143_208 (1).csv", encoding="ISO-8859-1", skiprows=3, sep=";", skipfooter=12, thousands=".", decimal=",", engine="python")

In [42]:
#Visualiza apenas as 5 primeiras: dados.head()
dados.head(20)

,Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
0,11 Rondônia,-,-,-,-,-,-,-,-,-,...,1.004562e+07,1.067725e+07,1.814712e+07,1.775385e+07,1.765986e+07,1.443590e+07,1.183444e+07,7.371335e+06,1682801.60,1.088060e+09
1,12 Acre,-,-,-,-,-,-,-,-,-,...,4.175526e+06,5.282655e+06,5.699598e+06,5.002273e+06,4.326882e+06,3.458187e+06,2.302711e+06,1.196755e+06,-,4.752903e+08
2,13 Amazonas,-,-,-,-,-,-,-,-,-,...,2.740646e+07,2.234104e+07,2.792379e+07,2.451592e+07,2.397354e+07,2.217540e+07,2.161494e+07,1.380696e+07,5292323.36,2.061943e+09
3,14 Roraima,-,-,-,-,-,-,-,-,-,...,3.557822e+06,4.172286e+06,5.427227e+06,4.192541e+06,3.681418e+06,3.475206e+06,3.320808e+06,2.907871e+06,1496814.75,3.525463e+08
4,15 Pará,-,-,-,-,-,-,-,-,-,...,3.904235e+07,3.711344e+07,4.962542e+07,5.255833e+07,5.090723e+07,4.387659e+07,3.371808e+07,2.083787e+07,4620263.03,4.968812e+09
5,16 Amapá,-,-,-,-,-,-,-,-,-,...,2.786277e+06,2.664375e+06,3.960131e+06,5.153705e+06,5.672087e+06,5.469150e+06,4.136951e+06,1.875242e+06,626751.41,3.371820e+08
6,17 Tocantins,-,-,-,-,-,-,-,-,-,...,8.868699e+06,9.098989e+06,1.012971e+07,9.762981e+06,1.016178e+07,6.349488e+06,4.610171e+06,2.304080e+06,312354.68,1.110345e+09
7,21 Maranhão,-,-,-,-,-,-,-,-,-,...,3.121035e+07,3.582465e+07,5.431570e+07,5.179777e+07,5.532468e+07,5.195857e+07,3.777543e+07,2.577967e+07,11194657.20,4.161326e+09
8,22 Piauí,-,-,-,-,-,-,-,-,-,...,2.183911e+07,2.041470e+07,3.158648e+07,3.236725e+07,3.255078e+07,2.601580e+07,1.997285e+07,1.522089e+07,9371428.06,2.450509e+09
9,23 Ceará,-,-,-,-,-,-,-,-,-,...,5.745159e+07,6.010552e+07,9.606387e+07,1.005437e+08,1.028260e+08,8.191945e+07,5.772714e+07,3.565001e+07,16234603.93,7.118540e+09
10,24 Rio Grande do Norte,-,-,-,-,-,-,-,-,-,...,2.745243e+07,2.834465e+07,3.714735e+07,3.841142e+07,4.181990e+07,3.443817e+07,2.453706e+07,1.680917e+07,6055806.12,2.867428e+09
11,25 Paraíba,-,-,-,-,-,-,-,-,-,...,2.174078e+07,2.332800e+07,3.219797e+07,3.090481e+07,3.960246e+07,3.314942e+07,2.492584e+07,1.616788e+07,8962429.99,2.796673e+09
12,26 Pernambuco,-,-,-,-,-,-,-,-,-,...,8.314499e+07,8.174186e+07,1.058719e+08,1.182180e+08,1.320957e+08,1.195459e+08,8.915630e+07,7.162584e+07,35603376.46,9.243658e+09
13,27 Alagoas,-,-,-,-,-,-,-,-,-,...,2.015429e+07,2.153984e+07,3.087517e+07,2.941400e+07,3.055069e+07,2.688825e+07,1.747591e+07,1.139388e+07,5714532.94,2.394793e+09
14,28 Sergipe,-,-,-,-,-,-,-,-,-,...,1.276518e+07,1.174258e+07,1.875020e+07,1.913666e+07,1.972061e+07,1.500772e+07,7.751833e+06,4.636421e+06,1509495.66,1.313873e+09
15,29 Bahia,-,-,-,-,-,-,-,-,-,...,8.821380e+07,9.687808e+07,1.178162e+08,1.159290e+08,1.342297e+08,1.205161e+08,9.569190e+07,6.164569e+07,24858284.14,1.049850e+10
16,31 Minas Gerais,-,-,-,-,-,-,-,-,-,...,1.928442e+08,1.838915e+08,2.613767e+08,2.555458e+08,2.751518e+08,2.497139e+08,1.947341e+08,1.391578e+08,60010941.33,2.189955e+10
17,32 Espírito Santo,-,-,-,-,-,-,-,-,-,...,4.066491e+07,3.952997e+07,5.761866e+07,5.803185e+07,5.734537e+07,4.813767e+07,3.655087e+07,2.712745e+07,11916897.69,3.710942e+09
18,33 Rio de Janeiro,-,-,-,-,-,-,-,-,-,...,1.034684e+08,8.751876e+07,1.257351e+08,1.329651e+08,1.453727e+08,1.249090e+08,1.136609e+08,9.413736e+07,43133058.07,1.113187e+10
19,35 São Paulo,40243.16,11449.99,34583.77,68556.52,39809.34,19904.67,19904.67,34532.40,23374.12,...,3.614271e+08,3.528464e+08,5.029056e+08,5.044272e+08,5.481127e+08,5.031610e+08,4.043732e+08,3.019863e+08,130535317.64,4.429079e+10

In [43]:
# traz as ultimas 5 linhas
dados.tail()

,Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
22,43 Rio Grande do Sul,-,-,-,-,-,-,-,-,-,...,1.159919e+08,1.267303e+08,1.696877e+08,1.453025e+08,1.550843e+08,1.428123e+08,1.128054e+08,74954589.62,25200345.68,1.361334e+10
23,50 Mato Grosso do Sul,-,-,-,-,-,-,-,-,-,...,2.472700e+07,2.560076e+07,3.250618e+07,3.310106e+07,3.688563e+07,3.159520e+07,2.071197e+07,11302985.98,2445267.12,2.516383e+09
24,51 Mato Grosso,-,-,-,-,-,-,-,-,-,...,1.888971e+07,2.154459e+07,3.579084e+07,3.753402e+07,3.785947e+07,3.493713e+07,2.936420e+07,19849249.43,7325067.61,2.386584e+09
25,52 Goiás,-,-,-,-,-,-,-,-,-,...,4.263870e+07,4.571547e+07,7.446406e+07,6.863041e+07,6.946733e+07,6.716235e+07,5.789129e+07,44939821.34,18860370.17,5.380179e+09
26,53 Distrito Federal,-,-,-,-,-,-,-,-,-,...,2.448472e+07,2.415606e+07,3.639103e+07,3.564176e+07,3.243456e+07,2.719646e+07,2.626552e+07,22156437.60,13173812.37,2.778457e+09

In [44]:
# Apresenta a estrutura do conjunto de dados, permitindo identificar tipos de variáveis, volume de dados e possíveis inconsistências
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Columns: 293 entries, Unidade da Federação to Total
dtypes: float64(170), object(123)
memory usage: 61.9+ KB

In [45]:
# dados.mean(numeric_only=True) - Calcula a média das colunas numéricas, ignorando colunas de texto (object)

dados_numericos = dados.select_dtypes(include='number')  # Seleciona apenas as colunas numéricas
dados_numericos.mean()  # Calcula a média dessas colunas

2007/Ago    3.049528e+05
2007/Set    7.881453e+05
2007/Out    2.440163e+06
2007/Nov    5.517354e+06
2007/Dez    1.233716e+07
                ...
2021/Mai    8.727186e+07
2021/Jun    7.759041e+07
2021/Jul    6.084629e+07
2021/Ago    4.388572e+07
Total       6.852321e+09
Length: 170, dtype: float64

In [48]:
# Padroniza a exibição de valores numéricos (float) com duas casas decimais, melhorando a legibilidade dos dados
pd.options.display.float_format = '{:.2f}'.format

In [50]:
dados_numericos.mean()

2007/Ago       304952.77
2007/Set       788145.26
2007/Out      2440162.96
2007/Nov      5517354.05
2007/Dez     12337159.42
                ...
2021/Mai     87271862.20
2021/Jun     77590406.47
2021/Jul     60846287.01
2021/Ago     43885716.30
Total      6852320913.49
Length: 170, dtype: float64

In [61]:
# desafio: Selecionar a coluna mais recente. Obs.: A ultima coluna é a Total, ignorar esta.
# iloc[linhas, colunas]. : → todas as linhas. [-2] → segunda coluna a partir do final. Pegue todas as linhas da penúltima coluna

dados.iloc[:, [-2]]

        2021/Set
0     1682801.60
1              -
2     5292323.36
3     1496814.75
4     4620263.03
5      626751.41
6      312354.68
7    11194657.20
8     9371428.06
9    16234603.93
10    6055806.12
11    8962429.99
12   35603376.46
13    5714532.94
14    1509495.66
15   24858284.14
16   60010941.33
17   11916897.69
18   43133058.07
19  130535317.64
20   32660877.10
21   18486461.58
22   25200345.68
23    2445267.12
24    7325067.61
25   18860370.17
26   13173812.37